
server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///git_stu
    username: root
    password: 123456
  thymeleaf:
    cache: false
dubbo:
  application:
    name: class_service
  protocol:
    port: 20881
  registry:
    address: zookeeper://192.168.182.111:2181